include("C:/Users/cgamboa/Documents/MIPSolver2017_08.jl/src/branch_and_bound.jl")
include("C:/Users/cgamboa/Documents/MIPTests.jl/miptests.jl")

function runtest(BNB::Function, solver::MathProgBase.AbstractMathProgSolver = JuMP.UnsetSolver())
@testset "Testes" begin
solver = GurobiSolver(OutputFlag=0)

      test1(BNB,solver)
      test2(BNB,solver)
      test3(BNB,solver)
      test3_2(BNB,solver)
      test3_3(BNB,solver)
      testCaminho(BNB,solver)
      testInfeasibleKnapsack(BNB,solver)
      testInfeasibleUC(BNB,solver)
      testRobustCCUC(BNB,solver)
      testSudoku(BNB,solver)
      testSudoku4x4(BNB,solver)
      testUnboundedKnapsack(BNB,solver)
      test_Minimal_UC(BNB,solver)
      test_P1_Brito(BNB,solver)
      test_PL_Infeasible_Brito(BNB,solver)
      test_PL_Infeasible_Raphael(BNB,solver)
      test_PL_Simples_Brito(BNB,solver)
      test_PL_Simples_Raphael(BNB,solver)
      test_PL_Unbounded_Brito(BNB,solver)
      test_feature_selection_grande(BNB,solver)
      test_feature_selection_medio(BNB,solver)
      test_feature_selection_pequeno_inviavel(BNB,solver)
      test_feature_selection_pequeno_viavel(BNB,solver)
      teste_PL_andrew_inviavel(BNB,solver)
      teste_PL_andrew_unbounded(BNB,solver)
      teste_PL_andrew_viavel(BNB,solver)
    end
end

runtest(BNB,GurobiSolver(OutputFlag=0))
